export const ErrorCode = {
  BAD_REQUEST:             'BAD_REQUEST',
  UNAUTHORIZED:            'UNAUTHORIZED',
  FORBIDDEN:               'FORBIDDEN',
  EMAIL_NOT_VERIFIED:      'EMAIL_NOT_VERIFIED',
  ACCOUNT_BANNED:          'ACCOUNT_BANNED',
  NOT_FOUND:               'NOT_FOUND',
  CONFLICT:                'CONFLICT',
  UNPROCESSABLE_ENTITY:    'UNPROCESSABLE_ENTITY',
  RATE_LIMIT_EXCEEDED:     'RATE_LIMIT_EXCEEDED',
  USER_CREATION_FAILED:    'USER_CREATION_FAILED',
  USER_UPDATE_FAILED:      'USER_UPDATE_FAILED',
  ACCOUNT_DELETION_FAILED: 'ACCOUNT_DELETION_FAILED',
  LOGOUT_FAILED:           'LOGOUT_FAILED',
  INVALID_RESET_TOKEN:     'INVALID_RESET_TOKEN',
  INTERNAL_ERROR:          'INTERNAL_ERROR',
} as const
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode]
